version: '2'
linters:
  default: all
  disable:
    - exhaustruct
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - testableexamples
        path: (.+)_test\.go
      - linters:
          - forbidigo
          - wrapcheck
        path: cmd/exampleapp
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
