version: '2'

linters:
  default: all
  disable:
    - exhaustruct
    - wsl
    - depguard
  exclusions:
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - path: (.+)_test\.go
        linters:
          - funlen
          - testableexamples
      - path: cmd/exampleapp
        linters:
          - forbidigo
          - wrapcheck
  settings:
    wsl_v5:
      allow-first-in-block: true
      branch-max-lines: 3

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
