# Simple go lint and test.
os: linux
dist: bionic
language: go
go:
  - 1.15.x
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
script:
  - GOOS=linux golangci-lint run --enable-all -D exhaustivestruct
  - GOOS=darwin golangci-lint run --enable-all -D exhaustivestruct
  - GOOS=windows golangci-lint run --enable-all -D exhaustivestruct
  - GOOS=freebsd golangci-lint run --enable-all -D exhaustivestruct
  - go test -race -covermode=atomic ./...
  # Test 32 bit OSes.
  - GOOS=linux GOARCH=386 go build .
  - GOOS=freebsd GOARCH=386 go build .
